apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: mysecrets
  namespace: default
spec:
  encryptedData:
    mysecret: {{ .Values.secrets.mysecret }}
  template:
    metadata:
      creationTimestamp: null
      name: mysecrets
      namespace: default
